baseURL = 'https://nim-italia.github.io/'
theme = "hugo-theme-learn"
languageCode = 'it-it'
title = 'Nim Italia'
description = "Documentazione italiana del linguaggio di programmazione Nim"

staticDir = ['static']
[params]
themeVariant = ['zen-dark', 'zen-light']
disableNextPrev = true
editURL = "https://github.com/nim-italia/nim-italia.github.io/edit/main/content/"
  [params.author]
    name = "Nim Italia"

